name: Slither Analysis
on: [push]
jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Run Slither
        uses: crytic/slither-action@v0.3.0
        id: slither
        with:
          node-version: 16
          fail-on: none
          slither-args: --filter-paths "openzeppelin,RIF,util" --exclude .github --checklist --markdown-root ${{ github.server_url }}/${{ github.repository }}/blob/${{ github.sha }}/
          target: .

      - name: Create Slack payload
        id: create-slack-payload
        run: |
             npm install -g md-to-pdf
             touch slither-output.md   
             echo -n '${{steps.slither.outputs.stdout }}' > slither-output.md
             md-to-pdf slither-output.md > slither-output.pdf
             
             
      - uses: MeilCli/slack-upload-file@v3
        with:
          slack_token: ${{ secrets.SLACK_TOKEN }}
          channel_id: 'C05UBKD9Y65'
          file_path: 'slither-output.pdf'
          initial_comment: 'Slither scan results for ${{github.repository}}'
      
