name: Solidity Lint Analysis
on: [push, pull_request]
permissions: {}

jobs:
  solidity-lint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2

      - name: Use Node.js 24.x
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 #v4.4.0
        with:
          node-version: 24

      - name: Install dependencies
        run: npm install

      - name: Run Solhint Analysis
        run: npm run lint:sol
